java_library(
    name = "magnet",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/autovalue",
        "//third_party/guava",
    ],
    visibility = [
        "//src/main/java/net/ajmichael/marauder/bittorrent/tracker:__pkg__",
        "//src/test/java/net/ajmichael/marauder/bittorrent/magnet:__pkg__",
    ],
)
