java_library(
    name = "tracker",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/net/ajmichael/marauder/bittorrent/magnet",
        "//third_party/autovalue",
        "//third_party/guava",
    ],
)
