java_test(
    name = "MagnetLinkContentsTest",
    srcs = ["MagnetLinkContentsTest.java"],
    deps = [
        "//src/main/java/net/ajmichael/marauder/bittorrent/magnet",
        "//third_party/guava",
        "//third_party/junit",
        "//third_party/truth",
    ],
    resources = [
        "good-magnet-link.txt",
    ]
)
